[package]
name = "testapp"
version = "0.1.0"
authors = ["Brent Allen <ballen@brentallen.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
k4a = { path = "../../lib/k4a" }